"""
The graph.

    route ──┬─ invoice ───→ extract → classify_and_cost → regulatory → verify → report
            ├─ duty_question ──────→ classify_and_cost ──────────────────────→ report
            └─ out_of_scope ───────────────────────────────────────────────→ report

Deliberately a fixed graph, not an autonomous agent loop.

arXiv 2603.07379 catalogues what goes wrong in free-roaming retrieval
loops: compounding hallucination, memory poisoning, retrieval
misalignment, cascading tool failure. Those risks buy nothing here,
because the sequence of steps for classifying an invoice is known in
advance. The judgement lives inside the nodes; the control flow does not
need to be discovered at runtime.

That is the answer to "why isn't this a ReAct agent?" — it is a choice
with a citation behind it, not a shortcut.
"""

from __future__ import annotations

import concurrent.futures
import contextvars

from langsmith import traceable

from backend.core.duty import calculate_duty
from backend.core.schemas import ItemAttributes, LineItem, LineItemResult
from backend.graph.router import pick_branch, route
from backend.graph.state import ShulkoState
from backend.tools.tariff_tool import HSCodeNotFound, lookup_rates

def _parallel(fn, jobs: list, workers: int | None = None) -> list:
    """Run per-item work concurrently, preserving the tracing context.

    Every line item needs its own LLM calls, and running an invoice's
    items one after another is what pushes a three-item invoice past a
    three-minute timeout. They are independent, so they run together.

    contextvars.copy_context() is not optional here: LangSmith carries the
    parent run in a context variable, and a bare thread starts outside it.
    Without this each item would appear as a separate root trace instead
    of a branch of the invoice's run, and the trace would stop being the
    story you can walk through on camera.
    """
    if len(jobs) <= 1:
        return [fn(job) for job in jobs]

    if workers is None:
        # Sized from the quota, not the CPU. More threads than the
        # per-minute budget allows just means more requests waiting on
        # the same token bucket.
        from backend.core.config import get_settings
        workers = max(get_settings().max_workers, 1)

    results = [None] * len(jobs)
    with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as pool:
        futures = {}
        for i, job in enumerate(jobs):
            ctx = contextvars.copy_context()
            futures[pool.submit(ctx.run, fn, job)] = i
        for future in concurrent.futures.as_completed(futures):
            results[futures[future]] = future.result()
    return results


OUT_OF_SCOPE_REPLY = {
    "en": "I only handle Bangladesh import duty and HS classification. "
          "Attach a commercial invoice, or ask about a tariff code.",
    "bn": "আমি শুধু বাংলাদেশের আমদানি শুল্ক আর HS classification নিয়ে কাজ করি। "
          "একটা commercial invoice দিন, অথবা কোনো tariff code নিয়ে জিজ্ঞেস করুন।",
}


# ------------------------------------------------------------------ nodes
@traceable(name="01_extract", run_type="chain")
def extract_node(state: ShulkoState) -> dict:
    from backend.agents.extractor import extract

    extracted = extract(state["raw_file_path"])
    return {
        "line_items": [i.model_dump() for i in extracted.items],
        "warnings": [] if extracted.items
                    else ["No line items could be read from the document."],
    }


@traceable(name="02_03_classify_and_cost", run_type="chain")
def classify_and_cost_node(state: ShulkoState) -> dict:
    """Classify each item, then compute its duty.

    Classification is a judgement, so an LLM makes it. The duty is
    arithmetic, so Python makes it. Keeping that seam sharp is the whole
    design: no number in the output was ever generated by a model.
    """
    from backend.agents.classifier import classify

    items = [LineItem(**i) for i in state.get("line_items", [])]
    if not items and state.get("question"):
        items = [LineItem(description=state["question"],
                          attributes=ItemAttributes())]

    freight = float(state.get("freight") or 0)
    insurance = float(state.get("insurance") or 0)
    importer_type = state.get("importer_type") or "commercial"

    # A typed question carries no prices. Computing on a value of zero
    # would return a confident "৳0.00 duty", which is worse than useless:
    # it looks like an answer. So we compute on a notional 100 and report
    # rates, which is what "what is the duty on X?" actually asks.
    notional = all(i.quantity * i.unit_price == 0 for i in items)
    if notional:
        freight = insurance = 0.0

    # Freight and insurance apply to the shipment, so split them across
    # items by value rather than charging each item the full amount.
    total_value = sum(i.quantity * i.unit_price for i in items) or 1.0

    def process(item: LineItem) -> dict:
        result = LineItemResult(item=item)
        try:
            candidates = classify(item)
        except Exception as exc:
            # One unclassifiable item must not discard the whole invoice.
            # The other items still carry usable numbers, and this one
            # says plainly why it does not.
            result.needs_review = True
            result.warnings.append(f"Classification failed for this item: {exc}")
            return result.model_dump()

        result.candidates = candidates

        if candidates:
            result.chosen_hs_code = candidates[0].hs_code
            share = (item.quantity * item.unit_price) / total_value
            try:
                rates = lookup_rates(candidates[0].hs_code)
                duty = calculate_duty(
                    fob=100.0 if notional else item.quantity * item.unit_price,
                    freight=freight * share,
                    insurance=insurance * share,
                    rates=rates,
                    importer_type=importer_type,
                )
                result.duty = duty.to_dict()
                result.rates_pct = {
                    "cd": round(rates.cd * 100, 2),
                    "rd": round(rates.rd * 100, 2),
                    "sd": round(rates.sd * 100, 2),
                    "vat": round(rates.vat * 100, 2),
                    "ait": round(rates.ait * 100, 2),
                    "at": round(rates.at * 100, 2),
                    "total_tax_incidence": duty.effective_rate,
                }
            except HSCodeNotFound as exc:
                result.needs_review = True
                result.warnings.append(str(exc))
        else:
            result.needs_review = True
            result.warnings.append("No tariff heading matched this item.")

        return result.model_dump()

    results = _parallel(process, items)
    return {"results": results, "notional": notional}


@traceable(name="04_regulatory", run_type="chain")
def regulatory_node(state: ShulkoState) -> dict:
    """Live regulatory check, deduplicated and capped.

    Grounded search is the slowest call in the pipeline, so it runs once
    per distinct HS code rather than once per line item, and only for the
    first few. arXiv 2605.06635 measured that searching deeper actually
    made factual accuracy worse by about 42% — so fewer, better-sourced
    checks is the accurate choice as well as the fast one.
    """
    from backend.agents.regulatory import check_regulations
    from backend.core.config import get_settings

    results = state.get("results", [])
    limit = get_settings().max_regulatory_checks

    unique: dict[str, str] = {}
    for r in results:
        code = r.get("chosen_hs_code")
        if code and code not in unique:
            unique[code] = r["item"]["description"]
        if len(unique) >= limit:
            break

    if not unique:
        return {"advisories": []}

    def check(pair):
        """Advisories are additive. If the search fails, the run keeps its
        duty figures and simply carries no advisory for that code."""
        code, description = pair
        try:
            result = check_regulations(code, description)
            return code, [a.model_dump() for a in result.advisories], result.mechanism
        except Exception as exc:
            print(f"[regulatory] check failed for {code}: {exc}")
            return code, [], "none"

    pairs = list(unique.items())
    found = _parallel(check, pairs)
    by_code = {code: items for code, items, _ in found}

    advisories = []
    for r in results:
        code = r.get("chosen_hs_code")
        r["advisories"] = by_code.get(code, [])
        advisories.extend(r["advisories"])

    # Report the strongest engine that actually ran. "none" for every code
    # means the grounding step produced nothing at all -- no key, or the
    # quota is gone -- and an empty advisory list then means "not checked",
    # not "nothing to declare". The report says which, because the two
    # carry opposite advice for the importer.
    ran = {mechanism for _, _, mechanism in found}
    mechanism = next(
        (m for m in ("google_search", "tavily") if m in ran), "none"
    )
    return {
        "advisories": advisories,
        "grounding": {
            "mechanism": mechanism,
            "available": mechanism != "none",
            "codes_checked": len(pairs),
        },
    }


@traceable(name="05_verify", run_type="chain")
def verify_node(state: ShulkoState) -> dict:
    from backend.agents.classifier import HSCandidate
    from backend.agents.verifier import verify

    results = state.get("results", [])

    def judge(result: dict):
        candidates = [HSCandidate(**c) for c in result.get("candidates", [])]
        try:
            return verify(result["item"]["description"], candidates)
        except Exception as exc:
            # The verifier exists to catch unsafe answers, so it failing
            # is itself a reason to flag rather than to wave through.
            from backend.agents.verifier import Verdict
            return Verdict(
                verdict="fail", needs_review=True,
                warnings=[f"Verification could not be completed ({exc}). "
                          "Treat this classification as unconfirmed."],
            )

    verdicts = _parallel(judge, results)

    needs_review = False
    warnings: list[str] = []
    for result, verdict in zip(results, verdicts):
        result["needs_review"] = result.get("needs_review") or verdict.needs_review
        result["warnings"] = result.get("warnings", []) + verdict.warnings
        needs_review = needs_review or result["needs_review"]
        warnings.extend(verdict.warnings)

    return {"needs_review": needs_review, "warnings": warnings}


@traceable(name="06_report", run_type="chain")
def report_node(state: ShulkoState) -> dict:
    lang = state.get("language", "en")

    if state.get("route") == "out_of_scope":
        return {"report": {"kind": "refusal",
                           "message": OUT_OF_SCOPE_REPLY.get(lang, OUT_OF_SCOPE_REPLY["en"])}}

    results = state.get("results", [])
    totals = {"av": 0.0, "tti": 0.0, "landed_cost": 0.0}
    for r in results:
        for key in totals:
            totals[key] += float((r.get("duty") or {}).get(key, 0.0))

    return {"report": {
        "kind": "rate_card" if state.get("notional") else "landed_cost",
        "items": results,
        "totals": {k: round(v, 2) for k, v in totals.items()},
        "effective_rate": round(totals["tti"] / totals["av"] * 100, 2) if totals["av"] else 0.0,
        "needs_review": state.get("needs_review", False),
        "advisories": state.get("advisories", []),
        "grounding": state.get("grounding") or {
            "mechanism": "none", "available": False, "codes_checked": 0,
        },
    }}


# ------------------------------------------------------------------ wiring
def build_graph():
    """Compile the state graph. Called once at API startup."""
    from langgraph.graph import END, StateGraph

    g = StateGraph(ShulkoState)

    g.add_node("route", route)
    g.add_node("extract", extract_node)
    g.add_node("classify_and_cost", classify_and_cost_node)
    g.add_node("regulatory", regulatory_node)
    g.add_node("verify", verify_node)
    g.add_node("report", report_node)

    g.set_entry_point("route")
    g.add_conditional_edges("route", pick_branch, {
        "invoice": "extract",
        "duty_question": "classify_and_cost",
        "out_of_scope": "report",
    })

    g.add_edge("extract", "classify_and_cost")
    g.add_edge("classify_and_cost", "regulatory")
    g.add_edge("regulatory", "verify")
    g.add_edge("verify", "report")
    g.add_edge("report", END)

    return g.compile()


_graph = None


def get_graph():
    global _graph
    if _graph is None:
        _graph = build_graph()
    return _graph
